### ISSUE TITLE
yakut replay

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/yakut#54]
A command is needed that accepts message objects expressed in YAML with metadata and publishes them on the specified subjects. The subject-ID, dtype, and publication period are to be sourced from the metadata as produced by `yakut subscribe` (the period is the delta of `ts_monotonic`):

```yaml
$ yakut sub 33:uavcan.si.unit.angle.scalar --with-metadata | jq
{
  "33": {
    "_meta_": {
      "ts_system": 1651525686.008718,
      "ts_monotonic": 1827560.239782,
      "source_node_id": 112,
      "transfer_id": 0,
      "priority": "nominal",
      "dtype": "uavcan.si.unit.angle.Scalar.1.0"
    },
    "radian": 2.309999942779541
  }
}
{
  "33": {
    "_meta_": {
      "ts_system": 1651525687.015653,
      "ts_monotonic": 1827561.247286,
      "source_node_id": 112,
      "transfer_id": 1,
      "priority": "nominal",
      "dtype": "uavcan.si.unit.angle.Scalar.1.0"
    },
    "radian": 2.309999942779541
  }
}
```

The intended usages are two:

1. Replaying data collected earlier with `yakut subscribe`
2. Publishing data produced by other software, e.g.:

```c
printf("{33: {_meta_: {ts_monotonic: 1827561.247286, dtype: uavcan.si.unit.angle.Scalar.1.0}, radian: %f}}\n", get_value());
```

If transfer-ID and source node-ID are specified, spoofing should be used.
