### ISSUE TITLE
For custom commands, allow yakut to read a map file

### ISSUE THREAD

**Issue by emrainey** [OpenCyphal/yakut#91]
The file could be yaml or json or ini, but would map commands in words to command numbers. It could be automatically read in from known location like a ~/.yakut/custom_commands.yaml

```
---
custom_commands:
    - number: 300
       name: foo
    - number: 301 
       name: bar
```
This would allow users to do:

`yakut cmd X foo` instead of `yakut cmd X 300` which is not descriptive.

These could be also checked for duplicates and limits (like predefined values).
